//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyxi.Muse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class play_logs
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int media_id { get; set; }
        public System.DateTime created { get; set; }
    }
}
