//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyxi.Muse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class media
    {
        public int id { get; set; }
        public int work_id { get; set; }
        public string name { get; set; }
        public string extension { get; set; }
        public long length { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public byte[] content { get; set; }
    }
}
